---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
        app: nodejs
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 081184234118.dkr.ecr.us-east-1.amazonaws.com/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
...

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8081
  type: NodePort
